## Image name: faucet/tests

FROM faucet/test-base:latest

COPY ./ /faucet-src/
WORKDIR /faucet-src/

RUN \
    apt-key adv --keyserver keyserver.ubuntu.com --recv-keys FFBE06FBB4EDC679174DD2CCD5AA2ED445128570 && \
    echo "deb http://ppa.launchpad.net/byllyfish/oftr/ubuntu xenial main" >> /etc/apt/sources.list && \
    apt-get update && \
    apt-get install oftr

CMD ["docker/runtests.sh"]
