## Image name: faucet/tests

FROM faucet/faucet-testbase:latest

ENV PIP="pip -q --no-cache-dir install --upgrade"
ENV PIP3="pip3 -q --no-cache-dir install --upgrade"

COPY ./ /faucet-src/
WORKDIR /faucet-src/

RUN \
    ./docker/base/retrycmd.sh "$PIP -r /faucet-src/test-requirements.txt" && \
    ./docker/base/retrycmd.sh "$PIP3 -r /faucet-src/requirements.txt" && \
    ./docker/base/retrycmd.sh "$PIP3 -r /faucet-src/test-requirements.txt" && \
    $PIP3 .

RUN \
    apt-key adv --keyserver keyserver.ubuntu.com --recv-keys FFBE06FBB4EDC679174DD2CCD5AA2ED445128570 && \
    echo "deb http://ppa.launchpad.net/byllyfish/oftr/ubuntu xenial main" >> /etc/apt/sources.list && \
    apt-get update && \
    apt-get install oftr && \
    cp /usr/sbin/tcpdump /usr/local/sbin/tcpdump

CMD ["docker/runtests.sh"]
